# Generated by Django 5.2.5 on 2025-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('tshirts', 'T-shirts'), ('shirts_blouses', 'Shirts/Blouses'), ('sweaters_hoodies', 'Sweaters/Hoodies'), ('tank_tops_camisoles', 'Tank Tops/Camisoles'), ('jeans', 'Jeans'), ('trousers_pants', 'Trousers/Pants'), ('shorts', 'Shorts'), ('skirts', 'Skirts'), ('dresses', 'Dresses'), ('jumpsuits', 'Jumpsuits'), ('jackets', 'Jackets'), ('coats', 'Coats'), ('blazers', 'Blazers'), ('raincoats_trenchcoats', 'Raincoats/Trenchcoats'), ('hats_caps', 'Hats/Caps'), ('scarves', 'Scarves'), ('belts', 'Belts'), ('gloves', 'Gloves'), ('sunglasses', 'Sunglasses'), ('jewelry', 'Jewelry'), ('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal_shoes', 'Formal Shoes'), ('underwear', 'Underwear'), ('bras', 'Bras'), ('pajamas', 'Pajamas'), ('lounge_sets', 'Lounge Sets')], max_length=50),
        ),
    ]
